# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lalamoveChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lalamoveChallenge
  pod 'Alamofire', '4.7.3'
  pod 'AlamofireImage', '3.3.1'
  pod 'SnapKit', '4.0.0'
  pod 'GoogleMaps', '2.7.0'

  target 'lalamoveChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lalamoveChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
